ccflags-y += -Idrivers/media/platform/msm/camera_v2_t2
ccflags-y += -Idrivers/media/platform/msm/camera_v2_t2/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2_t2/codecs
ccflags-y += -Idrivers/media/platform/msm/camera_v2_t2/isps
ccflags-y += -Idrivers/media/platform/msm/camera_v2_t2/pproc
ccflags-y += -Idrivers/media/platform/msm/camera_v2_t2/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2_t2/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2_t2/jpeg_10
ccflags-y += -Idrivers/media/platform/msm/camera_v2_t2/fd

obj-$(CONFIG_MSMB_CAMERA_T2) += msm.o
obj-$(CONFIG_MSMB_CAMERA_T2) += hw_camera_common.o
obj-$(CONFIG_MSMB_CAMERA_T2) += camera/
obj-$(CONFIG_MSMB_CAMERA_T2) += msm_vb2/
obj-$(CONFIG_MSMB_CAMERA_T2) += sensor/
obj-$(CONFIG_MSMB_CAMERA_T2) += pproc/
obj-$(CONFIG_MSMB_CAMERA_T2) += isp/
obj-$(CONFIG_MSMB_CAMERA_T2) += ispif/
obj-$(CONFIG_MSMB_JPEG) += jpeg_10/
obj-$(CONFIG_MSMB_CAMERA_T2) += msm_buf_mgr/
obj-$(CONFIG_MSMB_CAMERA_T2) += hw_camera_log.o

