ccflags-y += -Idrivers/media/platform/msm/camera_v2_t2/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_t2/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2_t2/sensor/cci
obj-$(CONFIG_MSMB_CAMERA_T2)   += msm_camera_io_util.o msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o
