ccflags-y += -Idrivers/media/platform/msm/camera_v2_t2
ccflags-y += -Idrivers/media/platform/msm/camera_v2_t2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_t2/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
