ccflags-y += -Idrivers/media/platform/msm/camera_v2_t2
ccflags-y += -Idrivers/media/platform/msm/camera_v2_t2/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_t2/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
